name: Update Recent Commit Badge

on:
  schedule:
    - cron: "*/30 * * * *"  # Every 30 mins
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get most recent commit
        id: commit
        run: |
          echo "Fetching most recent repository..."
          REPO=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/users/ericspencer00/repos?sort=updated&per_page=1" | jq -r '.[0].name')
          echo "Found repository: $REPO"
          
          echo "Fetching latest commit..."
          SHA=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/ericspencer00/$REPO/commits?author=EricSpencer00&?per_page=1" | jq -r '.[0].sha')
          echo "Found commit: $SHA"

          echo "repo=$REPO" >> $GITHUB_OUTPUT
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Write commit info to JSON
        run: |
          echo '{"schemaVersion":1,"label":"Most Recent Commit","message":"'${{ steps.commit.outputs.repo }}/${{ steps.commit.outputs.sha }}'","color":"blue"}' > recent-commit.json

      - name: Check for changes
        id: check
        run: |
          if git diff --quiet recent-commit.json; then
            echo "No changes detected"
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected"
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit & Push
        if: steps.check.outputs.changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add recent-commit.json
          git commit -m "🤖 update: recent commit badge"
          git push
