name: Update Recent Commit Badge

on:
  schedule:
    - cron: "*/30 * * * *"  # Every 30 mins
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Get most recent commit
        id: commit
        run: |
          echo "Fetching most recent repository..."
          REPO=$(curl -s "https://api.github.com/users/ericspencer00/repos?sort=updated&per_page=1" | jq -r '.[0].name')
          echo "Found repository: $REPO"
          
          echo "Fetching latest commit..."
          SHA=$(curl -s "https://api.github.com/repos/ericspencer00/$REPO/commits?per_page=1" | jq -r '.[0].sha' | cut -c1-7)
          echo "Found commit: $SHA"

          echo "repo=$REPO" >> $GITHUB_OUTPUT
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Write commit info to JSON
        run: |
          echo '{ "schemaVersion": 1, "label": "Most Recent Commit", "message": "'${{ steps.commit.outputs.repo }}/${{ steps.commit.outputs.sha }}", "color": "blue" }' > recent-commit.json

      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add recent-commit.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "update: recent commit badge" && git push)
